#+TITLE: Emacs Solidity Mode
#+AUTHOR: Lefteris Karapetsas

[[LICENSE][file:https://img.shields.io/badge/License-GPL%20v3-blue.svg]] [[http://melpa.org/#/solidity-mode][file:http://melpa.org/packages/solidity-mode-badge.svg]]

A simple language mode for the Solidity language. It is a constant work in progress as the
 language itself also progresses. For information about Solidity check the [[https://github.com/ethereum/wiki/wiki/Solidity-Tutorial][Tutorial]] and the [[https://github.com/ethereum/wiki/wiki/Solidity-Features][Features]] 
wiki pages.


* Installation
You can simply load the file in your emacs but the recommended way to install it is either via el-get or MELPA.

** El-get
If you don't know how to use el-get you can find more information on its [[https://github.com/dimitri/el-get][webpage]]. First [[https://github.com/dimitri/el-get#basic-setup][install el-get]] and then (in emacs), press =Alt+x= (this is in emacs notation written as =M-x= ) and then type =el-get-install=. This will prompt you for a package, type =solidity-mode= and hit enter, this should install all you need.

** Melpa
You can also obtain solidity-mode from [[http://melpa.org/#/][Melpa]] as can be seen [[http://melpa.org/#/solidity-mode][here]].

* Configuration
By default solidity-mode associates itself with any files ending in =.sol=.

If using =el-get= then you should have a specific package initializing lisp file. If not then you can put these
anywhere in your =init.el=.

** Generic configuration
Regardless of where you installed solidity mode from, you need to require the package:
#+BEGIN_SRC lisp
(require 'solidity-mode)
#+END_SRC
(append that line to your =~/.emacs= file)

** Interface with linters
*** Provide path to solc binary
The ~solc~ binary is assumed to be part of the PATH. Wherever that is not the case you would have to manually
set the location of the binary like below:
#+BEGIN_SRC emacs-lisp
(setq solidity-solc-path "/home/lefteris/ew/cpp-ethereum/build/solc/solc")
#+END_SRC

Note: This better be set before requiring solidity mode.

*** Provide path to solium binary
The ~solium~ binary is assumed to be part of the user's ~PATH~. If this is not the case
then set its location like below:
#+BEGIN_SRC emacs-lisp
(setq solidity-solium-path "/home/lefteris/.npm-global/bin/solium")
#+END_SRC


** [Optional] Flycheck interface
Solidity mode can also interface with [[https://github.com/flycheck/flycheck][flycheck]] if you have it. Make sure to
download and install the flycheck package. Then configure it to either work on
all modes or enable it only for solidity mode.

Flycheck can interface either with solc or with [[http://solium.readthedocs.io/en/latest/][solium]]. Choose the appropriate
linter to use by providing the following in your emacs init:

#+BEGIN_SRC emacs-lisp
(setq solidity-flycheck-active-checker "solium")
#+END_SRC

If you want to use ~"solc"~ replace ~"solium"~ with it.

Keep in mind that you need to provide the path to either solc or solium unless
emacs can already find it in your environment's ~PATH~. Even if you can call it
from the command line it does not mean that EMACS can see it as emacs may be started
by systemd at which point ~PATH~ is not fully populated.

* Features
+ Syntax highlighting
+ Indentation
+ On the fly syntax checking with flycheck
More features are planned, which would interface with the solidity libraries.
